###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing_extensions import TypeAlias
from typing import Dict, Generic, List, Optional, TypeVar, Union, Literal

from . import types
from .types import Checked, Check

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################

T = TypeVar('T')
class StreamState(BaseModel, Generic[T]):
    value: T
    state: Literal["Pending", "Incomplete", "Complete"]


class Add(BaseModel):
    tool_name: Optional[Literal["add_2_numbers"]] = None
    x: Optional[Union[float, Literal["previous_output"]]] = None
    y: Optional[float] = None

class Divide(BaseModel):
    tool_name: Optional[Literal["divide_two_numbers"]] = None
    x: Optional[Union[float, Literal["previous_output"]]] = None
    y: Optional[float] = None

class MISSING(BaseModel):
    tool_name: Optional[Literal["MISSING"]] = None

class Multiply(BaseModel):
    tool_name: Optional[Literal["multiple_two_numbers"]] = None
    x: Optional[Union[float, Literal["previous_output"]]] = None
    y: Optional[float] = None

class SmallerProblems(BaseModel):
    problem_statement: Optional[str] = None
    tool_chosen: Optional[Union["Add", "Subtract", "Divide", "Multiply", "MISSING"]] = None

class Subtract(BaseModel):
    tool_name: Optional[Literal["subtract_two_numbers"]] = None
    x: Optional[Union[float, Literal["previous_output"]]] = None
    y: Optional[float] = None
